const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {JSDOM}=require('jsdom');
test('vista previa con foto, restauración, partículas y editor',async()=>{
const dom=new JSDOM('<body><div class="top-actions"><span class="profile-avatar"><img src="/foto.png"></span></div><main id="view"></main><div id="preview"></div></body>',{url:'https://fit.test',runScripts:'outside-only'});const w=dom.window;w.setInterval=()=>0;
const data={coins:100,level:2,xp:100,next:100,animations:true,equipped:{frame:'frame-ruby'},catalog:[{id:'frame-halloween',name:'Halloween',description:'Fiesta',slot:'frame',price:50}],inventory:[],history:[{activity:'first-schedule',xp:30,created_at:new Date().toISOString()}],days:[],categories:[]};
const calls=[];const c={state:{admin:true,user:{id:'test',account_type:'admin'},view:'rewards'},toast:()=>{},client:{request:async(url,method,body)=>{calls.push({url,body});return {data:url.endsWith('/me')?data:{}};}},dialog:html=>{const d=w.document.createElement('dialog');d.innerHTML=html;w.document.body.append(d);d.close=()=>{d.dispatchEvent(new w.Event('close'));d.remove();};d.querySelector('[data-close]').onclick=()=>d.close();return d;}};
w.eval(fs.readFileSync(path.join(__dirname,'../web/dist/js/gamification.js'),'utf8'));
await w.FIT_REWARDS.profilePreview(c,w.document.querySelector('#preview'));w.document.querySelector('[data-preview-item]').click();assert.ok(w.document.querySelector('dialog img[src="/foto.png"]'));assert.equal(w.document.querySelectorAll('dialog .fit-frame-particles i').length,8);w.document.querySelector('[data-close]').click();assert.equal(w.document.body.dataset.fitframe,'frame-ruby');
await w.FIT_REWARDS.render(c);w.document.querySelector('[data-tab=editor]').click();await new Promise(r=>setTimeout(r,5));const form=w.document.querySelector('#style-editor');assert.ok(form);form.elements.name.value='Mi diseño';form.elements.effect.value='candy';w.document.querySelector('#style-try').click();assert.equal(w.document.querySelectorAll('dialog .fit-frame-particles i').length,8);w.document.querySelector('[data-close]').click();assert.equal(w.document.body.dataset.fitframe,'frame-ruby');assert.ok(!w.document.querySelector('#custom-reward-styles').textContent.includes('custom-preview'));dom.window.close();
});
test('la caché incluye todas las dependencias de entrada y del juego',()=>{const root=path.join(__dirname,'../web/dist'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');for(const file of ['index.html','juego-castor.html']){const html=fs.readFileSync(path.join(root,file),'utf8');for(const [,asset] of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(asset.startsWith('http'))continue;assert.ok(sw.includes('/'+asset),asset+' debe estar en caché');assert.ok(fs.existsSync(path.join(root,asset.split('?')[0])),asset+' debe existir');}}});
